version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./${PASSWD_FILE_DIR}:/etc/nginx/htpassw
      - ./${NGINX_CONF_FILE_PATH}:${nginx_conf_file_path_container}
      - ./${CERT_DIRECTORY}:${container_cert_directory}
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /var/run/docker.sock:/tmp/docker.sock:ro
  webapp:
    image: amyerke/webapp
    expose:
      - 3000
    volumes:
      - ~/.batchawsdeploy/:/root/.batchawsdeploy
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./container_variables.env
    environment:
      - HOST_ENVIRONMENT='AWS'
      - VIRTUAL_HOST=webapp.${COMMON_NAME}
      - VIRTUAL_PORT=3000
  webdemo:
    image: nginxdemos/hello
    expose:
      - 80
    env_file:
      - ./container_variables.env
    environment:
      - VIRTUAL_HOST=webdemo.${COMMON_NAME}
      - VIRTUAL_PORT=3000

